#mandatory, one of them or both
local_samples: local_samples.tsv

#Host filtering:

reference_genome: {'host':'human','filename':'GCA_000001405.28_GRCh38.p13'}

indexing_mem: 25000000

filter_with_Pathseq: False

#assembly
minimum_quality_base: 28
minimum_read_length: 50
sliding_window_size: 5
sliding_window_quality_threshold: 20
adapter_file_name: NexteraPE-PE.fa
adapter_removal_param1: 3
adapter_removal_param2: 25
adapter_removal_param3: 6
cov_cutoff: 5
spades_kmer_sizes: 21,33,55,77,99,111,127
minimum_contig_size: 500

#taxonomy profiling
##Kaiju
kaiju_database: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/progenomes
nodes_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/nodes.dmp
names_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/names.dmp
##Kraken2
kraken_database: /media/data/databases/kraken_DB
samples_read_length: 150
kraken_kmer_len: 35
##Bracken
read_threshold: 10
taxonomic_level: S
##Pathseq
pathseq_database: /media/data/databases/PathseqDB
kmer_size: 31
kmer_mask: 16 #K-mer masking allows mismatches to occur at one or more specified positions.
              #Masking the middle base is recommended to enhance host read detection.(see PathSeqBuildKmers doc)
min_clip_len: 60 #QC for Pathseq
min_score_identity : 0.9
identity_margin: 0.02
skip_host_align: true
divide_by_gen_len: true
##EZvir
ezvir_database: /media/data/databases/EZvir
virus_family: Hepatitis_E
##SURPI
surpi_database: /media/data/databases/SURPI
surpi_image: /scratch/master_students/Farid/
adapter_set: Truseq
quality: Illumina
num_cores: 55
xlsx_template_path: /scratch/master_students/Farid/microbiome_shotgun_pipeline_test/SURPI_summary_template.xlsx
##ganon
ganon_db_path: /media/data/databases/ganon_db
##rkmh
rkmh_reference: /media/data/databases/rkmh_db/reference.fa
rkmh_kmer_size: 15
rkmh_sketch_size: 1000
min_kmer_occurence: 100 #use k-mers that occur more than 10 times in the reads
min_read_match: 10 #filter reads that map to less than 10 references



###NCBI Entrez
email: 'farid.chaabane@unil.ch'
api_key: '72a84b34c0317bb34bac7efbb7c6bda59209'


###Tool_comparison
target_rank: species
target_value: percent
community_name: CF-metagenome-1

# virulence factor search
virulence_database: databases/virulence/sqlite_db/virulence.db
virulence_fasta: databases/virulence/merged/virulence_db_nr.faa

