#mandatory, one of them or both
local_samples: local_samples.tsv

#Host filtering:

reference_genome: {'host':'human','filename':'GCA_000001405.28_GRCh38.p13'}

indexing_mem: 25000000


#assembly
minimum_quality_base: 28
minimum_read_length: 50
sliding_window_size: 5
sliding_window_quality_threshold: 20
adapter_file_name: NexteraPE-PE.fa
adapter_removal_param1: 3
adapter_removal_param2: 25
adapter_removal_param3: 6
cov_cutoff: 5
spades_kmer_sizes: 21,33,55,77,99,111,127
minimum_contig_size: 500

#taxonomy profiling
kaiju_database: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/progenomes
nodes_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/nodes.dmp
names_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/names.dmp
#metagenomic profiling

# virulence factor search
virulence_database: databases/virulence/sqlite_db/virulence.db
virulence_fasta: databases/virulence/merged/virulence_db_nr.faa

