#Resources
num_cores: 55
job_memory_limit: 6 #If you expect your job to use 6GB
                    #Snakemake makes sure that the sum of all jobs memory do not exceed the total set by the flag 'resources' in the snakemake command
#Path of sample names table
local_samples: local_samples.tsv #table with fastq sample file names
skip_preprocess: False
#Host filtering:
reference_genome: {'host':'human','filename':'GCA_000001405.28_GRCh38.p13'}

indexing_mem: 25000000

filter_with_Pathseq: False

#QC
minimum_quality_base: 28
minimum_read_length: 50
sliding_window_size: 5
sliding_window_quality_threshold: 20
adapter_file_name: TruSeq3-SE.fa
adapter_removal_param1: 3
adapter_removal_param2: 25
adapter_removal_param3: 6

#Assembly
cov_cutoff: 5
spades_kmer_sizes: 21,33,55,77,99,111,127
minimum_contig_size: 1000



#Coverage
genomes_to_cover: path/to/dir/with/genomes
indexing_algorithm: "is" #bwa indexing algorithm for bwa. Use 'is' for fasta smaller than 2GB
minimum_seed_length: 19 #matches shorter than 19bp will be missed
band_width: 100 #Gaps longer than 100 will not be found
z_dropoff: 100 #Stop extension when the difference between the best and the current extension score is above |i-j|*A+INT
              #where i and j are the current positions of the query and reference, respectively, and A is the matching score.
              #Z-dropoff not only avoids unnecessary extension, but also reduces poor alignments inside a long good alignment
matching_score: 1
mismatch_penalty: 4
gap_open_penalty: 6
gap_extension_penalty: 1
minimum_alignment_score: 30

min_contig_ident: 95 #% Minimum contig indentity to ref genome



#Common rvdb database
common: True
fasta_name: U-RVDBv16.0.fasta

#taxonomy profiling
##Kaiju
kaiju_database: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/progenomes
nodes_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/nodes.dmp
names_dmp: /home/master_students/2019_Farid/tools_test/kaiju/db/kaiju_db_progenomes_2019-06-25/names.dmp
##Kraken2
kraken_database: /media/data/databases/kraken_DB
kraken2x_database: /media/data/databases/kraken_DB/Kraken2X
samples_read_length: 150
kraken_kmer_len: 35
##Bracken
read_threshold: 10
taxonomic_level: S
##Pathseq
pathseq_database: /media/data/databases/PathseqDB
kmer_size: 31
kmer_mask: 16 #K-mer masking allows mismatches to occur at one or more specified positions.
              #Masking the middle base is recommended to enhance host read detection.(see PathSeqBuildKmers doc)
min_clip_len: 60 #QC for Pathseq
min_score_identity : 0.9
identity_margin: 0.02
skip_host_align: true
divide_by_gen_len: true
#Pathseq outputs cumulated reads at each taxonomic level instead of assigning exact counts which are corrected by default (only works with an updated pathseq database)
#Taxa entries that are outdated and have more than 0 read counts are kept but not corrected
#When merging taxonomy tables for pathseq, read counts for outdated taxids are attributed to the previous taxonomic level

##EZvir
ezvir_database: /media/data/databases/EZvir
virus_family: Hepeviridea
min_cov: 20 #at least 20% genome coverage
##SURPI
surpi_database: /media/data/databases/SURPI
surpi_image: /scratch/master_students/Farid/
adapter_set: Truseq
quality: Illumina

xlsx_template_path: /scratch/master_students/Farid/microbiome_shotgun_pipeline_test/SURPI_summary_template.xlsx
##ganon
ganon_db_path: /data/databases/ganon_db/rvdb #Include the database prefix in the path
##rkmh
rkmh_reference: /media/data/databases/rkmh_db/reference.fa
rkmh_kmer_size: 15
rkmh_sketch_size: 1000
min_kmer_occurence: 100 #use k-mers that occur more than 10 times in the reads
min_read_match: 10 #filter reads that map to less than 10 references
##Centrifuge
centrifuge_index: /data/diag_pipeline_data/references/centrifuge_db/p_compressed+h+v

## Metaphlan
metaphlan_db: /data/databases/metaphlan

###NCBI Entrez
email: yourncbi@mail.com
api_key: apikey


###Tool_comparison
tools: {'surpi':'mapping','pathseq':'mapping','ezvir':'mapping','ganon':'k-mer','kraken2':'k-mer','kraken2x':'k-mer','kaiju':'k-mer','bracken':'k-mer','centrifuge':'k-mer','metaphlan':'marker'}
superkingdom: Viruses
target_rank: species
target_value: counts
community_name: communityname
reads_threshold: 100

##Parameters for calculating precision and recall
read-step: 10
max-read: 100000

# virulence factor search
virulence_database: databases/virulence/sqlite_db/virulence.db
virulence_fasta: databases/virulence/merged/virulence_db_nr.faa

